services:
  postgres:
    image: postgres:16
    container_name: postgres_mantenimiento
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mantenimiento
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d mantenimiento"]
      interval: 5s
      timeout: 3s
      retries: 5

  backend:
    build:
      context: ./backend-go
      dockerfile: Dockerfile
    container_name: mantenimiento_backend
    restart: always
    ports:
      - "1883:1883"
    environment:
      DATABASE_URL: "postgres://admin:admin@postgres:5432/mantenimiento?sslmode=disable"
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build:
      context: ./web-dashboard
      dockerfile: Dockerfile
    container_name: mantenimiento_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data: